# There is no R support.  Use a fake language
language: c
env:
  global:
    - R_LIBS_USER=~/R
    - R_LIBS=~/R:/usr/local/lib/R/site-library:/usr/lib/R/site-library:/usr/lib/R/library
before_install:
#  We want R 3.0 packages, official Travis images only provide 2.14
  - sudo add-apt-repository "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -cs)/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-get update
  - sudo apt-get install r-base-dev r-recommended qpdf
install:
  - R --version
  - R -e '.libPaths(); sessionInfo()'
#  CRAN packages required by PANDA
  - Rscript -e 'install.packages(c("ape", "picante", "pspline"), dep = TRUE, repos = c("http://cran.rstudio.com", "http://cran.r-project.org"))'
#  CRAN packages required by PANDA tests
  - Rscript -e 'install.packages(c("testthat", "vegan", "permute", "lattice", "nlme"), dep = TRUE, repos = c("http://cran.rstudio.com", "http://cran.r-project.org"))'
script:
  - R CMD build --no-manual .
  - R CMD INSTALL *gz
  - cd tests/testthat && Rscript -e 'library(methods);library(testthat);library(PANDA);source("test-fit-coal.r"); test_file("test-fit-coal.r", "summary")'

